# Generated by Django 2.0.3 on 2018-03-31 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
    ]
